name: Build and Deploy 

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Install Dependency
        run: |
          sudo apt update
          sudo apt install emacs

      - name: Checkout
        uses: actions/checkout@master
        with:
          persist-credentials: false

      - name: Build
        run: |
          make

      - name: Deploy to GH Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./public
